### ISSUE TITLE
Mentions plugin prevents KeyUp and Down from navigating the document

### ISSUE THREAD

**Issue by MykolaGolubyev** [VincentLoy/share-selected-text#11]
Using examples from here https://www.draft-js-plugins.com/plugin/mention
Create three lines of text
```
text text text
another text @Matthew
line of text
```
move cursor at the end of Mentions entity `Matthew`. Press UP and cursor stays in place

**Comment by VincentLoy** [comment]
Hello @MykolaGolubyev Sorry but I do not understand what's going on with mentions plugin. Can you please be more explicit ?

Thanks in advance.
