### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by dbaronov** [VincentLoy/share-selected-text#12]
This is a strange one: it does not work in IE 11 as complains about not being able to understand the parameteres with default empty values, paased into a function: 
`let sanitizeText = function (text, sociaType = '') {...}`

Converted into ES5,  still does not work and no errors this time.

**Comment by VincentLoy** [comment]
Hello @dbaronov 

Thanks for reporting this bug, as you can see, IE11 has no support for functions default parameters http://kangax.github.io/compat-table/es6/

The distribution file of the script is already converted in ES5.

If you find a fix, a contribution will be appreciated.

**Comment by dbaronov** [comment]
Managed to get this error on text select in IE11:
![image](https://user-images.githubusercontent.com/12451088/35808829-0a8e3d16-0a7f-11e8-992e-89fd32db762b.png)

**Comment by VincentLoy** [comment]
Mmh. It seems that there is an error in the generateTooltip function with IE 11. Maybe he's not able to make dynamics appendChild ... 

Let me konw if you find any solution.

Thanks :)

**Comment by dbaronov** [comment]
PR for your review is available here: https://github.com/VincentLoy/share-selected-text/pull/13 .

**Comment by VincentLoy** [comment]
Thanks a lot @dbaronov I'll check it out !

**Comment by VincentLoy** [comment]
Fixed in #13
