### ISSUE TITLE
height when calling the function?

### ISSUE THREAD

**Issue by v3nt** [VincentLoy/share-selected-text#15]
Is it possible to set the height when calling the function? Tried `tooltipHeight: '33', ` but no joy.

Or set it via css only?

**Comment by VincentLoy** [comment]
Hello @v3nt ! There is no params to customize the tooltip height. Anyway, you can override the CSS by injecting your own code. Stylings are very simple in this plugin, so I think that you'll can do the trick quickly.

Check the styles here: https://github.com/VincentLoy/share-selected-text/blob/master/dev/shareSelectedText.less
