### ISSUE TITLE
Facebook does not show at all

### ISSUE THREAD

**Issue by LubomirKurpel** [VincentLoy/share-selected-text#16]
All the other services are being well rendered inside the popup, but I am struggling with facebook. It just keeps hidden (actually it is not even in the code of popup when I try to inspect element)

I will try to debug and see what I can do. Anyway great module!

**Comment by LubomirKurpel** [comment]
Okay my bad. It works, but only when FB APP ID is set up. I thought that for basic sharing there is no need for app ID, but it looks like it is. Thanks a lot for a module!

**Comment by VincentLoy** [comment]
No problem @LubomirKurpel !

I think that was fixed in #14 and related on issue #8
