### ISSUE TITLE
Dash in URL

### ISSUE THREAD

**Issue by XavRsl** [VincentLoy/share-selected-text#17]
Hi!
My application uses anchor links so the URL contains a dash (#). Something like that :  
http://blabla.com/blogs/article1#comment2

I tried to make your plugin work but the text I was highlighting was not contained in the Twitter window. It's a URL problem. I guess it should be url encoded before passing it to the url attribute. In the getPageUrl function, you probably should return 
```
encodeURI(window.location.href)
````
Thanks.

**Comment by VincentLoy** [comment]
Thanks for reporting this issue. I'll take a look. If you already solve the problem, don't hesitate to contribute :)

**Comment by XavRsl** [comment]
All right. I'll do that ASAP

**Comment by VincentLoy** [comment]
Thanks @XavRsl , I'll take a look asap

**Comment by VincentLoy** [comment]
solved in #18
