### ISSUE TITLE
FB don't work

### ISSUE THREAD

**Issue by skazhikadyadya** [VincentLoy/share-selected-text#8]
Hi, thank you for your plugin. 

When I try to share selected text to Facebook it can't share text, only default link to page. On twitter it works ok.

My config:

```
    shareSelectedText('#zradoText', {
        tooltipClass: '',    // cool, if you want to customize the tooltip
        sanitize: true,      // will sanitize the user selection to respect the Twitter Max length (recommended)
        buttons: [           // services that you want to enable you can add :
            'twitter',       // - twitter, tumblr, buffer, stumbleupon, digg, reddit, linkedin, facebook
            'buffer',
            'facebook',
            'digg',
            'reddit',
            'linkedin'
        ],
        anchorsClass: '',    // class given to each tooltip's links
        twitterUsername: '', // for twitter widget, will add 'via @twitterUsername' at the end of the tweet.
        facebookAppID: 'hidden', // Can also be an HTML element inside the <head> tag of your page : <meta property="fb:APP_ID" content="YOUR_APP_ID"/>
        facebookDisplayMode: 'popup', //can be 'popup' || 'page'
        tooltipTimeout: 250  //Timeout before that the tooltip appear in ms
    });
```

**Comment by VincentLoy** [comment]
Hello @skazhikadyadya, I'm sorry but facebook don't allow to share custom text automatically in sharing popup like Twitter do. 

I just added the Facebook feature to allow you to share the page on various social media.
But if you know any trick to do it. Feel free to share it or to contribute :)

Thanks for using the plugin ! :)

**Comment by ckconant** [comment]
I believe using:
var facebookUrl = 'https://facebook.com/dialog/share?display=' + parameters.facebookDisplayMode + '&href=' + PAGE_URL + '&quote=' + text;

will append the selected text to facebook.

**Comment by skazhikadyadya** [comment]
Hi, ckconant, can you give me your version of plugin? Thank you.

**Comment by ckconant** [comment]
@skazhikadyadya same code, just update line 133 of the js with

`var facebookUrl = 'https://facebook.com/dialog/share?display=' + parameters.facebookDisplayMode + '&href=' + PAGE_URL + '&quote=' + text;`

**Comment by skazhikadyadya** [comment]
@ckconant, thank you.

**Comment by VincentLoy** [comment]
Is it actually working ?

**Comment by ckconant** [comment]
It appears to be.  Here is my example: http://www.chrisconantisawesome.com/select-text-test

**Comment by dbaronov** [comment]
Fixed here: https://github.com/VincentLoy/share-selected-text/pull/14, now part of the package, so this issue can be marked as resolved.

**Comment by VincentLoy** [comment]
Many thanks @dbaronov !!
